// <auto-generated />
using System;
using MauiTreasureHunter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MauiTreasureHunter.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MauiTreasureHunter.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPlaced")
                        .HasColumnType("bit");

                    b.Property<Guid>("TreasureItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TreasureItemId");

                    b.HasIndex("UserId", "IsPlaced")
                        .HasDatabaseName("IX_InventoryItems_UserId_IsPlaced");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("MauiTreasureHunter.Domain.Entities.TreasureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CollectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraphicResourcePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlacedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsCollected")
                        .HasDatabaseName("IX_TreasureItems_IsCollected");

                    b.ToTable("TreasureItems");
                });

            modelBuilder.Entity("MauiTreasureHunter.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMode")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfiles_Username");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MauiTreasureHunter.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("MauiTreasureHunter.Domain.Entities.TreasureItem", "TreasureItem")
                        .WithMany()
                        .HasForeignKey("TreasureItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MauiTreasureHunter.Domain.Entities.UserProfile", null)
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreasureItem");
                });

            modelBuilder.Entity("MauiTreasureHunter.Domain.Entities.TreasureItem", b =>
                {
                    b.OwnsOne("MauiTreasureHunter.Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("TreasureItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double?>("Altitude")
                                .HasColumnType("float")
                                .HasColumnName("Altitude");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("TreasureItemId");

                            b1.ToTable("TreasureItems");

                            b1.WithOwner()
                                .HasForeignKey("TreasureItemId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("MauiTreasureHunter.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
